_default:

    vcs: git

    prerequisites:
     - working-copy-check
     - display-last-changes

    version-generator:
        semantic:
            allow-label: true
    version-persister:
        vcs-tag:
            tag-prefix: "v"

    pre-release-actions:
        composer-update: ~
        changelog-update:
            format: semantic
            dump-commits: true
            exclude-merge-commits: true
        vcs-commit: ~

    post-release-actions:
        vcs-publish:
            ask-confirmation: false